version: '3'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub
    container_name: jupyterhub
    ports: 
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    environment:
      DOCKER_NOTEBOOK_IMAGE: jupyterlab_img
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
    restart: on-failure
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab-throaway
    network_mode: none
    command: echo
    environment:
      HTTP_PROXY: http://proxy.austria.local:8080
      HTTPS_PROXY: http://proxy.austria.local:8080

volumes:
  jupyterhub_data:

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
